// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uveqcoiihfairtffennw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2ZXFjb2lpaGZhaXJ0ZmZlbm53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTE5MzQsImV4cCI6MjA2NDI2NzkzNH0.pO2PIS1QRcmvIec8QpYgv2TjvV_GG8CFcw9FuZSFMrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);